sonata_admin:
    title: 'Liturgia Cheznous'
    dashboard:
        groups:
            app.admin.group.users:
                label: app.admin.group.users
                label_catalogue: App
                items:
                    - app.admin.user
                    - app.admin.headquarter
        
            app.admin.group.liturgy:
                label: app.admin.group.liturgy
                label_catalogue: App
                items:
                    - app.admin.liturgy
                    - app.admin.liturgy.text

            app.admin.group.subscriptions: ~

        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_SONATA_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
            
