sonata_admin:
    show_mosaic_button: false
    search: false
    title: 'Liturgia Cheznous'
    dashboard:
        groups:
          app.admin.group.users:
                keep_open:       true
                label: app.admin.group.users
                label_catalogue: App
                icon: '<i class="fa fa-user"></i>'
                items:
                    - app.admin.user
          app.admin.group.liturgy:
                keep_open:       true
                label: app.admin.group.liturgy
                label_catalogue: App
                icon: '<i class="fa fa-book"></i>'
                items:
                    - app.admin.liturgy
                    - app.admin.liturgy.text
                    - route: liturgy_text_assemble
                      label: assemble_action
        blocks:
          
            -
                class:    col-lg-9 col-xs-9          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     app.block.service.email_subscription   # block id # block id

            -
                class:    col-lg-2 col-xs-3          # twitter bootstrap responsive code
                position: bottom                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id # block id
                roles: ['ROLE_ADMIN']
                settings:
                    code:  app.admin.user    # admin code - service id
                    icon:  fa-user                  # font awesome icon
                    text:  app.user.stats.inactive  
                    color: bg-red
                    filters:                         # filter values
                        enabled: { value: 2 }

          
            -
                class:    col-lg-4 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                roles: ['ROLE_ADMIN']
                settings:
                    code:  app.admin.user    # admin code - service id
                    icon:  fa-user                  # font awesome icon
                    text:  app.user.stats.total            # static text or translation message
                    color: bg-aqua                 # colors: bg-green, bg-red and bg-aqua

            -
                class:    col-lg-2 col-xs-3          # twitter bootstrap responsive code
                position: bottom                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id # block id
                roles: ['ROLE_ADMIN']
                settings:
                    code:  app.admin.user    # admin code - service id
                    icon:  fa-user                  # font awesome icon
                    text:  app.user.stats.active  
                    color: bg-green
                    filters:                         # filter values
                        enabled: { value: 1 }
            -
                class:    col-lg-4 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  app.admin.liturgy    # admin code - service id
                    icon:  fa-book                  # font awesome icon
                    text:  app.liturgy.stats.total            # static text or translation message
                    color: bg-blue                 # colors: bg-green, bg-red and bg-aqua

            -
                class:    col-lg-4 col-xs-6          # twitter bootstrap responsive code
                position: bottom                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  app.admin.liturgy    # admin code - service id
                    icon:  fa-book                  # font awesome icon
                    text:  app.liturgy.stats.solemnities            # static text or translation message
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        isSolemnity: { value: 1 }
                        
#            - { type: sonata.admin.block.admin_list, position: left }
    security:
        handler: sonata.admin.security.handler.role
        role_admin: ROLE_SONATA_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
            
